# Generated by Django 5.0.3 on 2024-03-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.IntegerField(choices=[(1, 'mkldfv'), (2, 'admin')], default=1),
        ),
    ]
