# Generated by Django 5.0.3 on 2024-03-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test',
        ),
    ]
